name: keyboard_visibility
description: Flutter plugin for discovering the state of the soft-keyboard visibility on Android and iOS.
version: 1.0.0
author: <mappdevm@gmail.com>
homepage: https://github.com/softdev112/flutter_keyboard_visibility/tree/master

environment:
  sdk: '>=2.16.1 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

flutter:
  plugin:
    androidPackage: com.github.adee42.keyboardvisibility
    iosPrefix: FLT
    pluginClass: KeyboardVisibilityPlugin
